version: "3.9"
services:
  api:
    build:
      context: ./employees-api
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      DB_URL: employees
      PORT: 2000
    networks:
      - employees
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - employees
networks:
  employees:
    external: true
